daysUntilStale: 60
daysUntilClose: false
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be now be reviewed manually. Thank you
  for your contributions.
