language: android

jdk: oraclejdk8

install:
  - pip install --user 'requests[security]'

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # The BuildTools version used by your project
    - tools
    - build-tools-25.0.2
    - platform-tools
    # The SDK version used to compile your project
    - android-25
    # The support library
    - extra-android-m2repository


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

licenses:
  - '.+'

script: ./gradlew testdroidUploadKiwix && ./testdroid.py
