language: android

jdk: oraclejdk8

sudo: required

env:
  global:
    - secure: QFjd+jlUM8ca/z+d8opgi/7w8RYKkbmWxoJn9F3onUYctee/m57mHP6Xn/KtOwzPYlxATu7rNiS1oZCr8h48clMBtYBFhCBJDWNOJGQhG30mEoc37GXoszppROsSejinMWczBQlkBL6V/Vt96j6w17moc4DvloWNibmkS99hQqrFU12Jmqv//XIZ8gU+X9xduGs18Zaf5zWP0rWf3qt78FZ3DmDlzs+ZvYOfCk+ErMvX1cP45gAAKfvd9w6PlnaD8tz8BWdimB9fKzdFlBzxu79yMOFNFJgwFpfLH9Pvxe7SS2taX1QYIU+4CH3/gANQMKGG9YdTz098qSzda/4HSqhxhAmp6rFFl2ZqVvaf8i1B5bGC/F1P+/8iluDxZJv3OD7wa2zQ68HGT82AlnZJK42jF/fZBfQVZmV/wfTV3+0aQRCieNsd9k/vunRPhToxlVgPlcIkGnBVPB1AILz/rJPf7k6WjFWQHQU90bSvGEMdzD+K62rafGwZK6QYEeO9cJw6u/air4hGme9aMpinQnZW/8NmSmydYoqOkYt2fdoAyLVmEtx4IjOILZG9u2qxR0rnxV9rctfatsCt0gbeLG19ecS8ATiMUgch/IR4oiBbg4EGlDRHWkyu1r3HHqHWA+L3vy95r5wfsz8EaZ5Oxz5lyNQf4eep7VPr6+N4I9c=
    - secure: R8KHNMqrzfauW1C25YuuSNboX3cBXnSww/Dz+sX/TjT8hwMbs4AgxjtlLfcp+mMAKNRTdfd+1tqzSqXkafIk7/tBs3Q65HreQT3dF0UmWC6LWF/+l7/laH5qL8/QfuakLaAIU9FmLTao687pBhBepEpDi/62SoBwe6Njf4LihSaQ3dNhv7ORCgPCOVgaVFr5AU6iSNtpDVcTTRSvQLjk4bKrbbbXyGVyuV3PZ/1z+Dgnvtv9SS8PLOTDvCZVL1MhV/A603tYEFeZJru+sS9wW4sk5vjXfK4Quv4DXj3wxiQWaB4TTQWUF3U480dmXFRV+o2kBvqD1r1cCV9qOaH4FZno3cjdds/G6xNCdL/5CkNpX7naoB/SaySaLDY9RHL99EZcajj0HezCPy32fVvJ85B7phxO+9YNRdZDR4baj7exh05JMj8wR3snixCdaicRwsSpnmOXIWqXeBxhh//WvbohwamLl7mTbV9NzJRMKHFxj64/tBZ/obDvxdMPFf+szJb1SIrbW1A5sXhRr0AkD5JBLXZ9X8x43NOAwa9Ilx775OA3TzHlmbXE5rIu8FNn4msIDUd7NmF6dOO3kINmLAmrZbyzIoIJem7Ynox+4cN3N4on20pnIdlOpLuMrudnAuAOUjOTzRLfiPUigi3+okEGtY02qslZaJGchXHO2uM=
    - secure: E+gW494wF+PH7gMvJfwveuwcfOk70MXMERNLaBYXC1jNqy7EC7QimFNUrA1td6JdPMdZD304imfSrkDKQo+x4KCqDJNySdQCoYZGv7mC0Oma1RpBlIdhDBkpLPwI5Ii22KqI/uRH9H+Sl8lPz6b+ZsmNDhPQ+RTzpOyaDTxNBhQZPlQBvjhEzYG5h4T0J6d7wkALe0oWvq3xwt9bOmxu0kHBdYH1D5CRvEDp7X7hI9LssZoL4EeNhz/ZMjfWw4+Co2ZDyCdjIWHJ4Qa/RYcaDkUDDjrDlISAPYC2eqyRhmLEaO9k+c/cmNdEoEfCkMIQtPP43Sd/4dQpet2eI4QLXE0fw1aBwcUCQlhscUv7c9bFrCW1ydU/5PYDG17CXTW1LQCUns3m43o2WjGaEeOFX5lgqn8TlgWnUAsQacrAsYukeHVuC4xpR5RWTM4bu4Mxso7g2+KGLWwROQgmPL2tjQ5hoJ4E741xfCJbUvn38fX1QoRcu/PZS0Qnsu5yDRTl94TW/CZhgwV/ZzYE4mMn1hIlrG1nMTncXMl7LYzQcmZK/3rEoW7/P5vKca0MqFcMD9Mn3tagDGC/8APnasJ99uJluatuFjIq6NvHQ5mfTF8W1MQb1JNnOBVYRQXN2DrsAOmDSYNxdo+VbcIOYcNBVdlsDxJCvL76MIbTSrAaUZ0=
#    - ANDROID_TARGET=android-24
#    - ANDROID_ABI=arm64-v8a

before_install:
  - openssl aes-256-cbc -K $encrypted_87d19ee99c79_key -iv $encrypted_87d19ee99c79_iv -in secrets.tar.enc -out .\\secrets.tar -d
  - tar xvf secrets.tar

install:
  - pip install --user 'requests[security]'
  - wget -r -nH -nd -np -R index.html* robots.txt* http://download.kiwix.org/dev/android/api/licenses/ -e robots=off -P $ANDROID_HOME/licenses || true

addons:
  apt:
    packages:
      - lynx

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository
    #    - $ANDROID_TARGET
    #    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - ".+"

script:
  - ./gradlew lintKiwixDebug jacocoTestKiwixDebugUnitTestReport assembleKiwixRelease
  #  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 100M
  #  - emulator -avd test -no-window &
  #  - android-wait-for-emulator
  #  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  #  - adb shell input keyevent 82 & # unlock screen by pressing menu button
  #  - adb -e logcat *:D > logcat.log &
  #  - ./gradlew createKiwixDebugCoverageReport
  - if [$TRAVIS_PULL_REQUEST == “false” ] && [ $TRAVIS_BRANCH == “release” ]; then
    ./gradlew  publishKiwixRelease;
    fi
  - if  [$TRAVIS_TAG != “” ] && [$TRAVIS_PULL_REQUEST == “false” ] && [ $TRAVIS_BRANCH == “master” ]; then
    ./gradlew  publishKiwixRelease;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew testdroidUploadKiwixDebug

after_failure:
  - export LOG_DIR = ${TRAVIS_HOME}/build/kiwix/kiwix-android/app/build/outputs/reports/androidTests/connected/flavors/KIWIX/
  - lynx --dump ${LOG_DIR}com.android.builder.testing.ConnectedDevice.html
  - lynx --dump ${LOG_DIR}com.android.builder.testing.html
  - lynx -dump ${LOG_DIR}org.kiwix.kiwixmobile.tests.BasicTest.html;
  - echo " LOGCAT "; echo "========"; cat logcat.log; pkill -KILL -f adb