language: android

jdk: oraclejdk8

android:
  components:

install:
  - pip install --user 'requests[security]'
  - mkdir $ANDROID_HOME/licenses
  - wget -r -nH -nd -np -R index.html* mhutti1.eu/api/licenses/ -P $ANDROID_HOME/licenses
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

licenses:
  - '.+'

script: ./gradlew testdroidUploadKiwix && ./testdroid.py
