language: android

jdk: oraclejdk8

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-24.0.1
  - echo y | android update sdk -u -a -t android-24

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1

    - tools-2.2.3
    
    # The SDK version used to compile your project
    - android-24
  licenses:
    - '.+'
