name: Pull requests

on: [pull_request]

jobs:

  staticAnalysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Static Analysis
        run: ./gradlew ktlintCheck detekt app:lintDebug custom:lintCustomexampleDebug

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build all configurations
        run: ./gradlew assemble

      - name: Upload screenshot when build fails
        if: failure()
        run: adb shell screencap -p /sdcard/screencap.png && adb pull /sdcard/screencap.png && find screencap.png
